server:
  port: 8483
  servlet:
    session:
      cookie:
        name: auth-token
        http-only: true
        secure: false
        same-site: strict
      timeout: 5m

spring:
  application:
    name: redfox-authserver
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/redfox
    username: postgres
    password: postgres
  validation:
    method:
      adapt-constraint-violations: true
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8483
        client:
          webapp-client:
            registration:
              client-id: webapp-client
              client-secret: '{bcrypt}$2a$12$ZL6Gh4VdRlParif6TaWXQuvnVERcyeTx3t1W1/5YA.Vjrr/eMTUxm'
              client-authentication-methods:
                - client_secret_post
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:8482/oauth2/callback
              scopes:
                - openid
                - profile
            require-proof-key: true
            token:
              access-token-time-to-live: 2m
              refresh-token-time-to-live: 30d
              reuse-refresh-tokens: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    io.github.malczuuu.redfox: DEBUG

problem4j:
  detail-format: lowercase
