server:
  port: 8480

spring:
  application:
    name: redfox-gateway
  main:
    banner-mode: off
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: gateway-local
              uri: forward:///
              predicates:
                - Path=/oauth2/callback,/logout
              order: 1
            - id: redfox-app
              uri: ${redfox.gateway.app.base-url:http://localhost:8481}
              predicates:
                - Path=/api/**
              order: 100
            - id: redfox-webapp
              uri: ${redfox.gateway.webapp.base-url:http://localhost:8482}
              predicates:
                - Path=/**
              order: 200

redfox:
  gateway:
    cookie:
      secret: ${REDFOX_GATEWAY_COOKIE_SECRET:fRplKdOCutw+YqZjoDjRjuKWl0P2uFiHKniyi1Ipkok=}
    oauth2:
      client-id: redfox-gateway
      client-secret: ${REDFOX_GATEWAY_OAUTH2_CLIENT_SECRET:redfox-gateway-secret}
      authserver-url: ${REDFOX_GATEWAY_AUTHSERVER_BASE_URL:http://localhost:8483}
      redirect-uri: ${REDFOX_GATEWAY_OAUTH2_REDIRECT_URI:http://localhost:8480/oauth2/callback}

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
