global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "redfox-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["redfox-app:8080"]
  - job_name: "redfox-authserver"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["redfox-authserver:8080"]
