#
# This makes it possible to use @BeforeAll and @AfterAll without making them static, which is more
# convenient when using dependency injection in tests.
#
junit.jupiter.testinstance.lifecycle.default=per_class
