server:
  port: 8481

spring:
  application:
    name: redfox-app
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/redfox
    username: postgres
    password: postgres
  validation:
    method:
      adapt-constraint-violations: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8483

redfox:
  auth:
    authserver-token-uri: http://localhost:8483/oauth2/token
    client-id: webapp-client
    client-secret: webapp-secret
    cookie-domain: localhost
    cookie-secure: false
    refresh-cookie-max-age: 31d
    basic:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    io.github.malczuuu.redfox: DEBUG

problem4j:
  detail-format: lowercase
