server:
  port: 8481

spring:
  application:
    name: redfox-app
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/redfox
    username: postgres
    password: postgres
  validation:
    method:
      adapt-constraint-violations: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${REDFOX_AUTHSERVER_ISSUER:http://localhost:8483}

redfox:
  auth:
    authserver-token-uri: ${REDFOX_AUTHSERVER_TOKEN_URI:http://localhost:8483/oauth2/token}
    client-id: webapp-client
    cookie-domain: ${REDFOX_AUTH_COOKIE_DOMAIN:localhost}
    cookie-secure: ${REDFOX_AUTH_COOKIE_SECURE:false}

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

problem4j:
  detail-format: lowercase
